name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}

      - name: Run semantic-release
        run: npx semantic-release
        working-directory: ${{ github.workspace }}